version: 0.2

env:
  variables:
    GIT_BRANCH: "master"
    S3_URI: "s3://iop015-site-preview"
    # ID of the target distribution (for cache invalidation)
    CF_ID: E1H2TA6UU6TYW6

phases:
  install:
    commands:
      # - gem environment
      - gem install jekyll bundler

  pre_build: 
    commands: 
      - git checkout $GIT_BRANCH
      - cd docs
      - bundle install --path /root/vendor/bundle

  build: 
    commands: 
      - bundle exec jekyll build

  post_build:
    commands:
      - pwd
      # - cd ../
      - aws s3 sync ../docs/_site $S3_URI --delete
      - echo Files delivered to S3 bucket $S3_URI
      - aws cloudfront create-invalidation --distribution-id $CF_ID --paths /\*
      - echo CloudFront cache $CF_ID invalidated

artifacts:
  name: archive.zip
  files:
    - '**/*'
  discard-paths: no
  base-directory: docs/_site/


cache: 
  paths:
    - '/root/vendor/**/*'
